ano/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('msg.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

msg/urls.py
from django.urls import path
from . import views 
from .views import SignUpView,PostCreateView,PostDeleteView,IndeView
urlpatterns = [
    path('', IndeView.as_view(), name='ome/'),
    path('homes', views.IndexView, name='Home/'),
    path('logout/', views.logout, name='logout/'),
    path('post/<str:pk>/', views.postr, name="post_detail/"),
    path('comment/<str:pi>/', views.comment_lock, name="comment_lock/"),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='pdelete/'),
    
]

msg/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post (models.Model):
    
    text = models.TextField(max_length=1000)
    name = models.ForeignKey(User,on_delete=models.CASCADE,related_name='ano_name')
    nickname = models.CharField(max_length=14)
    date_created= models.DateTimeField(auto_now_add=True,null=True)
    def __str__(self):
        return self.text 
    
    def get_absolute_url(self):
        return reverse ('post_detail/',args=[self.nickname])
    
    
class Comment (models.Model):
    
    post = models.ForeignKey(Post, null=True,on_delete=models.CASCADE,related_name='comments')
    
    text = models.TextField(max_length=1000)
    
    date_created= models.DateTimeField(auto_now_add=True,null=True)
    active = models.BooleanField(default=True)
    def __str__(self):
        return self.text

msg/forms.py
from django import forms
#from django.contrib.auth.models import User
from .models import Comment
#from django.contrib.auth import get_user_model


class CommentForm (forms.ModelForm) :
    
    class Meta :
        model = Comment
        fields=('text',)
        
        
#from .models import Comment
#class CommentForm(forms.ModelForm):
# class Meta:
 #model = Comment
 #fields = ('name', 'email', 'body')
 
 
 

msg/views.py
from django.shortcuts import render,get_object_or_404
from .models import Comment,Post
from .forms import CommentForm
from django.shortcuts import redirect
from django.views.generic import ListView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.models import User

# Create your views here.

class IndeView(ListView):
    model = Post
    template_name = 'msg/inde.html'
    context_object_name = 'ur'
    
 #view post           
def IndexView (request):
    if request.user:
        current_user = request.user
        a = current_user.id
        b = Post.objects.filter(name_id = a)
        #b = Post.objects.all()
        return render (request, 'msg/index.html', {'b':b})
        
    else:
        return render (request, 'msg/post.html')
        
#comments section
def postr (request,pk):
    current_user = request.user
    ad = current_user.id
    post = Post.objects.get(nickname=pk)
    comm = None
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comm = form.save(commit=False)
            comm.post = post
            comm.save()
    
    else:
	    form = CommentForm()
    
    return render(request,'msg/post.html',{'post':post,'comm':comm,'form':form,'ad':ad})
#view comments
@login_required(login_url='login')    
def comment_lock (request,pi):
    current_user = request.user
    ad = current_user.id
    post = get_object_or_404(Post,pk=pi)
    comments = post.comments.filter(active=True)
    
    return render(request,'msg/detail.html',{'post':post,'comments':comments,'ad':ad})
#logout    
def logout (request):
    return render (request,'registration/logout.html')
#signup 
class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'register/register.html'
    
#create post    
class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    template_name = 'msg/create.html'
    fields = ['nickname', 'text']
    login_url = 'login' 
    def form_valid(self, form): # new
        form.instance.name = self.request.user
        return super().form_valid(form)

#delete post    
class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView): # new
    model = Post
    template_name = 'msg/delete.html'
    success_url = reverse_lazy('Home/')
    login_url = 'login' 
    def test_func(self): # new
        obj = self.get_object()
        return obj.name == self.request.user
    
    
    
    
    
    
    
    
    
    
    
    
    

msg/templates/msg/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

 {% block title %} <title>welcme to anony_msg</title>{% endblock %}

  <!-- Bootstrap core CSS -->
  <link href="{% static 'msg/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'msg/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav id="black" class="navbar navbar-expand-lg navbar-dark bg-black static-top navbar-custom">
    <div class="container">
      <button type="button" class="btn btn-transparent">
      <img src="{% static 'msg/img/comment.png' %}" id="comm-img"> <span id="dan" class="badge badge-danger">4</span>
      </button>
      <a class="navbar-brand" href="{% url 'ome/' %}">anony_msg</a>
      
      <button id="tog" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span id="tog" class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'Home/' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Signup</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'create' %}">Create New Post</a>
          </li>
          
          
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'msg/js/jquery.slim.min.js' %}"></script>
  <script src="{% static 'msg/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'msg/js/vue.min.js' %}"></script>
  <script src="{% static 'msg/js/style.js' %}"></script>

</body>

</html>

msg/templates/msg/create.html
{% extends 'msg/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>New post</h1>
 <form action="" method="post">
  {% csrf_token %}
    {{ form|crispy }}
 <input type="submit" value="Save" />
 </form>
{% endblock %}

msg/templates/msg/delete.html
{% extends 'msg/base.html' %}
{% block content %}
<style>
#delete {
  margin-top: 30px;
  
}

.bt {
  margin-bottom: 4px;
}
  
</style>
<div id="delete" style="color:#4a4a68" class="card bg-dark container">
<h1 style="color:white">Delete post</h1>
 <form action="" method="post">
     {% csrf_token %}
     <p style="color:white">Are you sure you want to delete "{{ post.text }}"?</p>
     <input class="bt btn btn-info" type="submit" value="Confirm" />
 </form>
 </div>
{% endblock %}

msg/templates/msg/detail.html
{% extends 'msg/base.html' %}
{% block title %}<title>{{ post.name }} comment page</title>{% endblock %}
{% block content %}
<style>
  #ctt {
    border-radius: 5%;
    border-color: blue;
    margin-top: 4px;
  }
  
  .bg-none {
    background: rgb(34,34,55);
  }
  
  #fl {
    float: left;
  }
</style>
<div class="container">
{% if ad == post.name_id %}
<h5 style="color:#e8d361">{{post.name}} comments</h5>
{% with comments.count as total_comments %}
 <h6 style="color:#5dad5dc4">
 {{ total_comments }} comment{{ total_comments|pluralize }}
 </h6>
 {{ comment.text|linebreaks }}
{% endwith %}
{% for comment in comments %}
<div id="ctt" class="card text-center bg-none">
    <h3 id="fl" style="color:#9f8d8db6">Message :</h3>
    <h4 id="fl" style="color:#9f8d8db6">{{ comment.text|linebreaks }}</h4>
    <h5 style="color:#9f8d8db6"><cite>by</cite> anonymous [ {{ comment.date_created }} ]</h5>
    </li>
</ul>
</div>
{% endfor %}
{% else %}
<div class="card">
<h1 style="color:#9f8d8db6">can't view {{post.name}} comments section because you are not the owner </h1>
</div>
{% endif %}
</div>
{% endblock %}

msg/templates/msg/inde.html
{% extends 'msg/base.html' %}
{% load static %}
{% block content %}
  <div class="container-fluid card-deck cold ">
    <div id="cold" class="card">
      <h1 id="wor">welcome to anony_msg.</h1>
      <h3 id="war">Let friends write anonymous message to you without knowing who wrote it and see their reaction about you and let them express how they love you.</h3>
      <div id="grides">
        <img id="png" src="{% static 'msg/img/user.png' %}">
        <img id="png" src="{% static 'msg/img/curved2.png' %}">
        <img id="png" src="{% static 'msg/img/browser.png' %}">
        <img id="png" src="{% static 'msg/img/curved1.png' %}">
        <div id="gridess">
          <img id="png" src="{% static 'msg/img/angry.svg' %}">
          <img id="png" src="{% static 'msg/img/happy-2.svg' %}">
          <img id="png" src="{% static 'msg/img/in-love.svg' %}">
          <img id="png" src="{% static 'msg/img/kissing.svg' %}">
          <img id="png" src="{% static 'msg/img/unhappy.svg' %}">
          <img id="png" src="{% static 'msg/img/angry-1.svg' %}">
          
        </div>
        <img id="png" src="{% static 'msg/img/curved3.png' %}">
        <img id="png" src="{% static 'msg/img/message.png' %}">
      </div>
      {% if user.is_authenticated %}
      <button id="gr"><a id="words" href="{% url 'Home/' %}"> view post</a></button>
      {% else %}
      <div id="gride">
        <button id="gr"><a id="words" href="{% url 'signup' %}">Signup</a></button>
        <button id="gr"><a id="words" href="{% url 'login' %}">Login</a></button>
      </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

msg/templates/msg/index.html
{% extends 'msg/base.html' %}
{% block content %}
<html>
  {% if user.is_authenticated %}
  <div class="container">
   <p id="usern">Hi {{ user.username }}!</p>
   <p id="create"><a href="{% url 'create' %}"><button class="btn btn-success">+ Create Post </button></a></p>
   
  {% else %}
   <p>You are not logged in.</p>
   <a href="{% url 'login' %}">Log In</a>
   <a href="{% url 'signup' %}">Signup</a>
  {% endif %}
  
  {% for br in b %}
  <div id="home" class="card">
  <h2>{{br.text}}<a id="warn" href=" {% url 'post_detail/' br.nickname %}"><button class="btn btn-warning">click to view</button></a> 
      <p><a id="danger" href="{% url 'pdelete/' br.pk %}"><button class="btn btn-danger">Delete Post</button></a></p>
  
  </h2>
  </div>
  {% endfor %}
 </div>
</html>
{% endblock %}

msg/templates/msg/post.html
{% extends 'msg/base.html' %}
{% block title %}<title>{{ post.text }}</title>{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<style>
  #postt {
    margin-top: 6px;
  }
  #btc {
    margin-bottom: 4px;
  }
  
  #id_text {
    float: center;
    width: 195px;
    height: 40px;
    border-radius: 5%;
  }
  
  #commt {
    border-radius: 5%;
    float: right;
    margin-right: 70px;
    margin-bottom: 30px;
  }
  
  #lar {
    font-size: 15px;
  }
</style>
<div id="postt"  class="container">
<div class="card text-center bg-dark">
<div class="card-body">
<h1 id="lar" style="color:white">{{post.text}}</h1>
</div>
<footer style="color:white" class="blockquote-footer">By<cite title="Source Title">{{post.nickname}}</cite></footer>
<div class="card-footer text-muted">
<h3 id="lar" style="color:white">{{post.date_created}}</h3>
</div>
{% if user.is_authenticated %}
{% if ad == post.name_id %}
<a id="btc" class="btn btn-primary" href="{% url 'comment_lock/' post.id %}">see comment</a>
{% endif %}
{% else %}
<h1>        </h1>
{% endif %}
</div>


{% with comments.count as total_comments %}
 <h2>
{% if user.is_authenticated %}
 {{ total_comments }} comment{{ total_comments|pluralize }}
 </h2>
{% else %}
 <h1>        </h1>
{% endif %}
{% endwith %}
<h3 style="color:gold">Write Your Comment</h3>
<form action="" method="post">
  {{ form|crispy }}
  {% csrf_token %}
  <input id="commt" style="margin-bottom:6px" class="btn btn-success" type="submit" value="Add comment">
</form>

{% endblock %}

msg/templates/register/register.html
{% extends 'msg/base.html' %}
{% block content %}

<style>
  /*#id_username,#id_password1,#id_password2 {
    float: right;
    font-size: 6px;
    padding-top: 5px;
  }*/
  
 p label {
    float: left;
    color: white;
  }
</style>
<div id class="container-fluid card border border-primary rounded-bottom bg-transparent">
{% load crispy_forms_tags %}
<form method="POST" class="uniForm">
    
    {% csrf_token %}
      {{ form|crispy }}
    <button type="submit" class="btn btn-success">Register</button>
</form>
</div>
{% endblock %}